### PR TITLE
Event locations map on main site

### PR DESCRIPTION
**Pull request by EerierGosling**

### CODE REVIEW

**Review by NeonGamerBot-QK — APPROVED** [review]

**Comment by Monoverde888** [comment]
why isn’t this merged?

**Review by AdamEXu — CHANGES_REQUESTED** [review]
We're Counterspell Silicon Valley on all public facing materials, not South Bay.

**Comment by EerierGosling** [comment]
This is out of date - I'm gonna make it import data from the Counterspell Airtable before merging so it doesn't need to be continuously updated

**Comment by AdamEXu** [comment]
got it :)

**Comment by EerierGosling** [comment]
replacing with #85

**Pull request closed without merging**
